### PR TITLE
Add support for Ruby 2.1. Remove Gemfile.lock

### PR DESCRIPTION
**Pull request by sunnyrjuneja**
I found that the library wasn't building on Ruby 2.1 despite the fact that it should support it no problem. I made the required changes to the Gemfile to do so.

Ruby best practices advices not to check in the [Gemfile.lock](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/) into version control while developing a gem.

### CODE REVIEW

**Comment by konklone** [comment]
No problem - you want to actually do a `git rm` on the `Gemfile.lock` file though? It's still in the repo.

**Comment by sunnyrjuneja** [comment]
Are you sure? I'm seeing in the PR that it isn't and I ran `git rm -f Gemfile.lock`.

**Comment by konklone** [comment]
Er, whoops, I looked too fast, sorry. Merging! Thank you!

**Comment by sunnyrjuneja** [comment]
No problem. Thanks for the fast response :).

**Pull request merged**
